#!/usr/bin/env bash
# Script to display DNS record info for given subdomains

dns_conf() {
    IP=$(dig +short "$2.$1")
    echo "$2 $IP" | awk '{print "The subdomain "$1" is a A record and points to "$2}'
}

if [ "$#" -eq 1 ]; then
    dns_conf "$1" "www"
    dns_conf "$1" "lb-01"
    dns_conf "$1" "web-01"
    dns_conf "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    dns_conf "$1" "$2"
fi
