#!/usr/bin/env bash
# Script to query subdomain names and record types

dns_conf () {
    result=$(dig +short "$2.$1")
    if [ -n "$result" ]; then
        type=$(dig "$2.$1" +short ANY | grep -Eo 'IN\s+[A-Z]+' | awk '{print $2}' | head -n1)
        echo "The subdomain $2 is a $type record and points to $result"
    else
        echo "The subdomain $2.$1 does not resolve."
    fi
}

if [ "$#" -eq 1 ]; then
  dns_conf "$1" "www"
  dns_conf "$1" "lb-01"
  dns_conf "$1" "web-01"
  dns_conf "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  dns_conf "$1" "$2"
else
  echo "Usage: $0 domain [subdomain]"
fi
