#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install Nginx

# Update and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Set "Hello World!" as default index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to listen on port 80 as default (IPv4 and IPv6)
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default

# Start nginx (without systemctl)
sudo service nginx start
